"""add assessment_answers_column

Revision ID: 1dc07e8cb930
Revises: 
Create Date: 2026-07-10 11:54:11.525814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1dc07e8cb930'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_projects_id'), table_name='user_projects')
    op.drop_table('user_projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_readiness_evaluations_id'), table_name='readiness_evaluations')
    op.drop_index(op.f('ix_readiness_evaluations_target_role'), table_name='readiness_evaluations')
    op.drop_table('readiness_evaluations')
    op.drop_index(op.f('ix_user_notifications_user_id'), table_name='user_notifications')
    op.drop_table('user_notifications')
    op.drop_index(op.f('ix_user_skills_id'), table_name='user_skills')
    op.drop_index(op.f('ix_user_skills_skill'), table_name='user_skills')
    op.drop_table('user_skills')
    op.drop_index(op.f('ix_skill_embeddings_id'), table_name='skill_embeddings')
    op.drop_index(op.f('ix_skill_embeddings_skill'), table_name='skill_embeddings')
    op.drop_table('skill_embeddings')
    op.drop_index(op.f('ix_query_queue_id'), table_name='query_queue')
    op.drop_index(op.f('ix_query_queue_query'), table_name='query_queue')
    op.drop_table('query_queue')
    op.drop_index(op.f('ix_opportunities_company'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_external_hash'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_title'), table_name='opportunities')
    op.drop_table('opportunities')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('external_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('opportunity_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('application_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('required_experience', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('required_skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('preferred_skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('allowed_branches', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('allowed_batches', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('min_cgpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('posted_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deadline_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('stipend', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_remote', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('description_embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('title_embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('opportunities_pkey'))
    )
    op.create_index(op.f('ix_opportunities_title'), 'opportunities', ['title'], unique=False)
    op.create_index(op.f('ix_opportunities_id'), 'opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_opportunities_external_hash'), 'opportunities', ['external_hash'], unique=True)
    op.create_index(op.f('ix_opportunities_company'), 'opportunities', ['company'], unique=False)
    op.create_table('query_queue',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('query', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('adapter', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cooldown_hours', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_run', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('next_run', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('failure_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('query_queue_pkey'))
    )
    op.create_index(op.f('ix_query_queue_query'), 'query_queue', ['query'], unique=True)
    op.create_index(op.f('ix_query_queue_id'), 'query_queue', ['id'], unique=False)
    op.create_table('skill_embeddings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('skill', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('skill_embeddings_pkey'))
    )
    op.create_index(op.f('ix_skill_embeddings_skill'), 'skill_embeddings', ['skill'], unique=True)
    op.create_index(op.f('ix_skill_embeddings_id'), 'skill_embeddings', ['id'], unique=False)
    op.create_table('user_skills',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('skill', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('domain', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_skills_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_skills_pkey'))
    )
    op.create_index(op.f('ix_user_skills_skill'), 'user_skills', ['skill'], unique=False)
    op.create_index(op.f('ix_user_skills_id'), 'user_skills', ['id'], unique=False)
    op.create_table('user_notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('opportunity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notification_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('read_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('user_notifications_opportunity_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_notifications_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_notifications_pkey'))
    )
    op.create_index(op.f('ix_user_notifications_user_id'), 'user_notifications', ['user_id'], unique=False)
    op.create_table('readiness_evaluations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('target_role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('overall_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('skills_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('projects_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('resume_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('missing_skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('recommended_projects', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('recommended_courses', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('recommended_certifications', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('resume_feedback', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('readiness_evaluations_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('readiness_evaluations_pkey'))
    )
    op.create_index(op.f('ix_readiness_evaluations_target_role'), 'readiness_evaluations', ['target_role'], unique=False)
    op.create_index(op.f('ix_readiness_evaluations_id'), 'readiness_evaluations', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('otp_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('otp_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('college', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('graduation_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cgpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('github_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('linkedin_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('resume_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('career_interests', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('experience', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('experience_duration', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('profile_embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('opportunity_preferences', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text('\'["Internship"]\'::json'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('user_projects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('domain', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('skills_used', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_projects_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_projects_pkey'))
    )
    op.create_index(op.f('ix_user_projects_id'), 'user_projects', ['id'], unique=False)
    # ### end Alembic commands ###
